### ISSUE TITLE
Question: Upload sketches from i2c Master with Ethernet webgui to i2c address slaves?

### ISSUE THREAD

**Issue by NonaSuomy** [mihaigalos/miniboot#20]
Would this bootloader allow you to update the sketches on many i2c Arduino slaves from an Arduino ethernet master. Like, say the master runs a website with an input box where you would select a compiled Arduino sketch in hex and select the slave address you want to upload on the i2c bus, which would then dump to the sketch to the appropriate i2c slave address on the bus?

[Master] Basically a Leonardo with Ethernet (wiznet)
https://www.dfrobot.com/product-1286.html

**Upload sketch from webgui to i2c slave @ address 10 on the bus**
blinkaddr10.hex/select addr10 => Webgui => ethernet => [Master]DFR0342 => i2c => address10 => [Slave@Addr10]ArduinoMicroEtc (slave 10 changed to new sketch uploaded)

**Upload sketch from webgui to i2c slave @ address 11 on the bus**
blinkaddr11.hex/select addr11 => Webgui => ethernet => [Master]DFR0342 => i2c => address11 => [Slave@Addr11]ArduinoMicroEtc (slave 11 changed to new sketch uploaded)

Thanks!

**Comment by mihaigalos** [comment]
So miniboot "pulls" data from a specific address.
You need to create a protocol on top of miniboot to mitigate accessing of the i2c bus, since access is exclusive to 2 devices at a time.
You need to:
- Sequentially inform each slave to reboot
- After reboot, each slave will pull the firmware from the master and reflashes
